version: '3'
services:
  php:
    container_name: php
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/

  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - sql-data:/var/lib/mysql
      - ./db/scheme:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  sql-data: