version: '3'
services:
  php:
    container_name: php
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    #volumes:
    #  - ./:/var/www/html/
    #entrypoint: ["./docker-php-entrypoint.sh", "docker-php-entrypoint"]
    ports:
      - 80:80
    links:
      - db
    env_file:
      - ./dev.env

  db:
    container_name: db
    image: mysql:8.0
    env_file:
      - ./dev.env
    volumes:
      - sql-data:/var/lib/mysql
      - ./db/scheme:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  sql-data: