version: '3'
services:
  php:
    container_name: php
    image: php:${PHP_TAG}
    volumes:
      - ./:/var/www/html/
    entrypoint: ["./docker-php-entrypoint.sh", "docker-php-entrypoint"]
    ports:
      - 80:80
    links:
      - db
    environment: 
      DB_HOST: "${DATABASE_HOST}"
      DB_DATABASE: "${DATABASE_NAME}"
      DB_USERNAME: "${USER}"
      DB_PASSWORD: "${USER_PASSWORD}"

  db:
    container_name: db
    image: mysql:${DB_TAG}
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "${USER}"
      MYSQL_PASSWORD: "${USER_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - sql-data:/var/lib/mysql
      - ./db/scheme:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  sql-data: